# Header
menu:
  Home: /
  Project Definition: /Project-Definition
  Twitter: https://twitter.com/StartNao
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: StartNao
google_plus:
fb_admins:
fb_app_id: